const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,deps={},extras={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>deps[n],Buffer,AbortSignal,process:{env:{WP_APP_PASSWORD:'test:secret'}},...extras});return exports;}
const selection=load('lib/stock-selection.ts');const stock={productId:5798,variable:true,available:true,variants:[{id:5801,available:true,attributes:[{name:'color',option:'Burgundy'},{name:'size',option:'S'}]},{id:5800,available:false,attributes:[{name:'color',option:'Burgundy'},{name:'size',option:'M'}]}]};
test('matches exact size and colour independently of parent availability',()=>{assert.equal(selection.stockForSelection(stock,'M','Burgundy').available,false);assert.equal(selection.stockForSelection(stock,'S','Burgundy').available,true);assert.equal(selection.stockForSelection(stock,'M','Burgundy').id,5800);assert.equal(selection.stockForSelection(stock,'S','Blue').available,false);});
test('does not label unqueried inventory sold out',()=>assert.equal(selection.stockForSelection(null,'M','Burgundy'),null));
const response={NextResponse:{json:(body,options)=>({body,status:options?.status||200})}};
test('restock signup requires a valid email and product',async()=>{const route=load('app/api/restock/route.ts',{'next/server':response},{fetch:async()=>{throw new Error('must not call')}});assert.equal((await route.POST({json:async()=>({email:'bad',productId:1})})).status,400);});
test('restock signup persists the selected variation without enrolling in a newsletter',async()=>{let body;const route=load('app/api/restock/route.ts',{'next/server':response},{fetch:async(url,options)=>{assert.ok(url.endsWith('/missus/v1/restock'));body=JSON.parse(options.body);return {ok:true,json:async()=>({ok:true})}}});const result=await route.POST({json:async()=>({email:'USER@example.com',productId:5798,variationId:5800})});assert.equal(result.status,200);assert.deepEqual(body,{email:'user@example.com',productId:5798,variationId:5800});});
test('signup never claims success when WordPress rejects or fails to persist',async()=>{for(const upstream of [{ok:false,status:503,json:async()=>({})},{ok:true,json:async()=>({})}]){const route=load('app/api/restock/route.ts',{'next/server':response},{fetch:async()=>upstream});assert.equal((await route.POST({json:async()=>({email:'user@example.com',productId:5798,variationId:5800})})).status,503);}});
