const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function service(fail=false){const exports={};const calls=[];let count=0;const carts=new Map();vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/woocommerce-shipping.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,process:{env:{}},AbortSignal,crypto:{randomUUID:()=>String(++count)},fetch:async(url,options)=>{calls.push({url,...options});const body=options.body?JSON.parse(options.body):null;let token=options.headers['Cart-Token'];let data={};if(url.includes('/cart?')){token='cart-'+count;carts.set(token,{subtotal:0});}else{assert.ok(carts.has(token),'requests must use the isolated cart token');if(url.includes('/products/'))data={attributes:[{name:'size',taxonomy:'pa_size',has_variations:true,terms:[{name:'M',slug:'medium'}]}]};if(url.endsWith('/cart/add-item')){assert.equal(body.variation[0].value,'medium');carts.get(token).subtotal+=body.quantity*50000;}if(url.endsWith('/cart/update-customer')){const lagos=body.shipping_address.state==='LA';assert.equal(body.shipping_address.country,'NG');data={shipping_rates:[{shipping_rates:[{rate_id:'flat_rate:37',method_id:'flat_rate',instance_id:37,name:'Standard',price:lagos?'400000':'700000',taxes:'0',currency_code:'NGN',currency_minor_unit:2},{rate_id:'flat_rate:38',method_id:'flat_rate',instance_id:38,name:'Express',price:lagos?'600000':'1300000',taxes:'0',currency_code:'NGN',currency_minor_unit:2},{rate_id:'terminal_delivery30',method_id:'terminal_delivery',instance_id:30,name:'Terminal',price:'0',taxes:'0',currency_code:'NGN',currency_minor_unit:2},...(carts.get(token).subtotal>=150000?[{rate_id:'free_shipping:41',method_id:'free_shipping',instance_id:41,name:'Free Shipping',price:'0',taxes:'0',currency_code:'NGN',currency_minor_unit:2}]:[])]}]};}}const stockFailure=fail==='stock'&&url.endsWith('/cart/add-item');return {ok:!stockFailure&&fail!==true,status:stockFailure?400:fail===true?503:200,headers:{get:()=>token},json:async()=>stockFailure?{message:"You cannot add &quot;Lexi - Burgundy, M&quot; because it is out of stock."}:data};}});return {...exports,calls};}
const address=state=>({address_1:'Test',city:'Test',state,country:'Nigeria'});const items=quantity=>[{productId:1,name:'Dress',size:'M',quantity}];
test('uses WooCommerce zone prices and filters unpriced Terminal placeholder',async()=>{const s=service();assert.deepEqual(Array.from(await s.getWooCommerceShippingRates(address('FCT Abuja'),items(1)),r=>r.amount),[700000,1300000]);assert.deepEqual(Array.from(await s.getWooCommerceShippingRates(address('Lagos'),items(1)),r=>r.amount),[400000,600000]);});
test('preserves free-shipping eligibility calculated by WooCommerce',async()=>{const s=service();assert.equal((await s.getWooCommerceShippingRates(address('Lagos'),items(3)))[0].method_id,'free_shipping');assert.equal((await s.getWooCommerceShippingRates(address('Lagos'),items(1))).some(r=>r.method_id==='free_shipping'),false);});
test('separate quotes never reuse a cart and coupons are applied before calculating rates',async()=>{const s=service();await Promise.all([s.getWooCommerceShippingRates(address('Lagos'),items(1),'SAVE'),s.getWooCommerceShippingRates(address('FCT Abuja'),items(1))]);assert.equal(new Set(s.calls.filter(c=>c.url.includes('/cart?')).map(c=>c.url)).size,2);const apply=s.calls.find(c=>c.url.endsWith('/cart/apply-coupon'));assert.equal(JSON.parse(apply.body).code,'SAVE');});
test('upstream failure cannot return fallback prices',async()=>{await assert.rejects(service(true).getWooCommerceShippingRates(address('Lagos'),items(1)));});
test('normalizes Nigerian states and existing codes',()=>{const s=service();for(const state of ['FCT Abuja','Abuja','FC','NG:FC'])assert.equal(s.normalizeShippingAddress(address(state)).state,'FC');});

test('stock errors identify the unavailable variation without masking it as a shipping outage',async()=>{const s=service('stock');await assert.rejects(s.getWooCommerceShippingRates(address('Lagos'),items(1)),error=>error instanceof s.CartAvailabilityError && error.message.includes('"Lexi - Burgundy, M"'));});
test('product availability checks use cart stock validation before checkout',async()=>{const s=service();await s.validateCartAvailability(items(1));assert.ok(s.calls.some(c=>c.url.endsWith('/cart/add-item')));assert.ok(!s.calls.some(c=>c.url.endsWith('/cart/update-customer')));});
